### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by liesun1994** [franckbrl/morpheval_v2#1]
Hi, I am using morpheval_v2 to evaluate translation quality. When using "evaluate_de.py", an error occurred, which is "ZeroDivisionError: division by zero". How to solve this problem? Thanks~

**Comment by franckbrl** [comment]
Hi, did you use the required version of SMOR mentioned here? https://github.com/franckbrl/morpheval_v2#requirements

**Comment by liesun1994** [comment]
ohhhhh! that's it !!
